// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Planty",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Planty",
            targets: ["AppModule"],
            bundleIdentifier: "com.noora.Planty3",
            teamIdentifier: "39YZX5T634",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To classify plant images using the camera."),
                .photoLibrary(purposeString: "To select images from the library for plant classification."),
                .photoLibraryAdd(purposeString: "To save classified images to the user's photo library.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/PlantyClassification.mlmodelc"),
                .copy("Resources/plantyINFO.csv")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)